name: Update the docs
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: |
        sudo apt install qrencode nasm -y
        nasm snake.asm -o docs/snake.com -f bin
        cd docs
        xxd -p snake.com > snake.hex
        python update.py
        qrencode -r snake.com -8 -o snake.png
        cd ..
        rm ./demo/snake.zip
        zip ./demo/snake.zip ./docs/snake.com
        git config --global user.email "just4now666666@gmail.com"
        git config --global user.name "donno2048"
        git add .
        git commit -m "update docs and demo"
        git push
        git subtree push --prefix demo origin gh-pages
