on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'demo/snake.zip'
      - 'demo/snake.png'
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  deploy:
    if: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt install qrencode nasm python3 -y
        nasm snake.asm -o docs/snake.com -f bin
        cd docs
        xxd -p snake.com > snake.hex
        python3 update.py
        qrencode -r snake.com -8 -o snake.png
        rm ../demo/snake.zip
        zip ../demo/snake.zip snake.com
        cd ..
        git config --global user.email "just4now666666@gmail.com"
        git config --global user.name "donno2048"
        git add .
        git commit -m "update docs and demo"
        git push
    - uses: actions/configure-pages@v3
    - uses: actions/upload-pages-artifact@v2
      with:
        path: 'demo/'
    - uses: actions/deploy-pages@v2
